<?php /** @var \TripFuser\MageSample\Block\Adminhtml\City\AddEdit $block */ ?>
<?php /** @var \Magento\Framework\Data\Form $form */ ?>
<?php $form = $block->getForm(); ?>
<div id="popup-modal" style="display: none">
    <?php echo '<form ', $form->serialize($form->getHtmlAttributes()), ' class="tf-admin-form">';?>
    <?php echo $form->getElement('city_id')->toHtml();?>
    <div class="clearfix row-gutter">
        <div class="col-m-6">
            <?php echo $form->getElement('country_id')->toHtml();?>
        </div>
    </div>
    <div class="clearfix row-gutter">
        <div class="col-m-6">
            <?php echo $form->getElement('region_id')->toHtml();?>
        </div>
    </div>
    <div class="clearfix row-gutter">
        <div class="col-m-6">
            <?php echo $form->getElement('default_name')->toHtml();?>
        </div>
    </div>
    <div class="clearfix row-gutter">
        <div class="col-m-6">
            <?php echo $form->getElement('location')->toHtml();?>
        </div>
    </div>
    <?php echo $form->getElement('callback-url')->toHtml();?>
    <?php echo '</form>';?>
</div>

<div id="confirm_init" style="display: none">
    <span id="action_delete" style="display: none"></span>
    <?php echo __("Are you sure you want to delete selected item?");?>
</div>